FROM node:latest AS node
WORKDIR /kafka-producer-starter
COPY . .
RUN npm install
RUN npm run build -- --c devtest

FROM nginx:1.17.1-alpine
COPY --from=node /kafka-producer-starter/dist/kafka-producer-starter/ /usr/share/nginx/html